import { User, UserID } from "../../pages/ChatFriendPage/types";

// 임시 유저 정보
export function getUser(userId: string): User {
    const userData: User = dummyUsers.filter(user => {
        return user.id === userId;
    })[0]
    return userData;
}

export function getUserID(userId: string): UserID {
    const userData: User = dummyUsers.filter(user => {
        return user.id === userId;
    })[0]
    return ({ userID: userData.id, userName: userData.name + `(${userData.nick})` })
}

export const dummyUsers: User[] = [
    {
        id: "1",
        name: "김철수",
        nick: "철수1",
        email: "chulsoo1@example.com",
        overallRank: 1,
        overallScore: 950,
        praiseRank: 1,
        praiseScore: 300,
        solveRank: 1,
        solveScore: 500,
        battleRank: 1,
        battleScore: 150,
    },
    {
        id: "2",
        name: "이영희",
        nick: "영희2",
        email: "younghee2@example.com",
        overallRank: 2,
        overallScore: 920,
        praiseRank: 2,
        praiseScore: 290,
        solveRank: 2,
        solveScore: 470,
        battleRank: 2,
        battleScore: 160,
    },
    {
        id: "3",
        name: "박민수",
        nick: "민수3",
        email: "minsoo3@example.com",
        overallRank: 3,
        overallScore: 890,
        praiseRank: 3,
        praiseScore: 280,
        solveRank: 3,
        solveScore: 450,
        battleRank: 3,
        battleScore: 160,
    },
    {
        id: "4",
        name: "최은지",
        nick: "은지4",
        email: "eunji4@example.com",
        overallRank: 4,
        overallScore: 870,
        praiseRank: 4,
        praiseScore: 270,
        solveRank: 4,
        solveScore: 440,
        battleRank: 4,
        battleScore: 160,
    },
    {
        id: "5",
        name: "김지훈",
        nick: "지훈5",
        email: "jihun5@example.com",
        overallRank: 5,
        overallScore: 850,
        praiseRank: 5,
        praiseScore: 260,
        solveRank: 5,
        solveScore: 430,
        battleRank: 5,
        battleScore: 160,
    },
    {
        id: "6",
        name: "이지은",
        nick: "지은6",
        email: "jieun6@example.com",
        overallRank: 6,
        overallScore: 830,
        praiseRank: 6,
        praiseScore: 250,
        solveRank: 6,
        solveScore: 420,
        battleRank: 6,
        battleScore: 160,
    },
    {
        id: "7",
        name: "오수민",
        nick: "수민7",
        email: "soomin7@example.com",
        overallRank: 7,
        overallScore: 810,
        praiseRank: 7,
        praiseScore: 240,
        solveRank: 7,
        solveScore: 410,
        battleRank: 7,
        battleScore: 160,
    },
    {
        id: "8",
        name: "윤하나",
        nick: "하나8",
        email: "hana8@example.com",
        overallRank: 8,
        overallScore: 790,
        praiseRank: 8,
        praiseScore: 230,
        solveRank: 8,
        solveScore: 400,
        battleRank: 8,
        battleScore: 160,
    },
    {
        id: "9",
        name: "정대현",
        nick: "대현9",
        email: "daehyun9@example.com",
        overallRank: 9,
        overallScore: 770,
        praiseRank: 9,
        praiseScore: 220,
        solveRank: 9,
        solveScore: 390,
        battleRank: 9,
        battleScore: 160,
    },
    {
        id: "10",
        name: "한지민",
        nick: "지민10",
        email: "jimin10@example.com",
        overallRank: 10,
        overallScore: 750,
        praiseRank: 10,
        praiseScore: 210,
        solveRank: 10,
        solveScore: 380,
        battleRank: 10,
        battleScore: 160,
    },
    {
        id: "11",
        name: "홍길동",
        nick: "길동11",
        email: "gildong11@example.com",
        overallRank: 11,
        overallScore: 730,
        praiseRank: 11,
        praiseScore: 200,
        solveRank: 11,
        solveScore: 370,
        battleRank: 11,
        battleScore: 160,
    },
    {
        id: "12",
        name: "강은비",
        nick: "은비12",
        email: "eunbee12@example.com",
        overallRank: 12,
        overallScore: 710,
        praiseRank: 12,
        praiseScore: 190,
        solveRank: 12,
        solveScore: 360,
        battleRank: 12,
        battleScore: 160,
    },
    {
        id: "13",
        name: "조영민",
        nick: "영민13",
        email: "youngmin13@example.com",
        overallRank: 13,
        overallScore: 690,
        praiseRank: 13,
        praiseScore: 180,
        solveRank: 13,
        solveScore: 350,
        battleRank: 13,
        battleScore: 160,
    },
    {
        id: "14",
        name: "김나연",
        nick: "나연14",
        email: "nayeon14@example.com",
        overallRank: 14,
        overallScore: 670,
        praiseRank: 14,
        praiseScore: 170,
        solveRank: 14,
        solveScore: 340,
        battleRank: 14,
        battleScore: 160,
    },
    {
        id: "15",
        name: "문성민",
        nick: "성민15",
        email: "sungmin15@example.com",
        overallRank: 15,
        overallScore: 650,
        praiseRank: 15,
        praiseScore: 160,
        solveRank: 15,
        solveScore: 330,
        battleRank: 15,
        battleScore: 160,
    },
    {
        id: "16",
        name: "이서연",
        nick: "서연16",
        email: "seoyeon16@example.com",
        overallRank: 16,
        overallScore: 630,
        praiseRank: 16,
        praiseScore: 150,
        solveRank: 16,
        solveScore: 320,
        battleRank: 16,
        battleScore: 160,
    },
    {
        id: "17",
        name: "박하준",
        nick: "하준17",
        email: "hajun17@example.com",
        overallRank: 17,
        overallScore: 610,
        praiseRank: 17,
        praiseScore: 140,
        solveRank: 17,
        solveScore: 310,
        battleRank: 17,
        battleScore: 160,
    },
    {
        id: "18",
        name: "윤지호",
        nick: "지호18",
        email: "jiho18@example.com",
        overallRank: 18,
        overallScore: 590,
        praiseRank: 18,
        praiseScore: 130,
        solveRank: 18,
        solveScore: 300,
        battleRank: 18,
        battleScore: 160,
    },
    {
        id: "19",
        name: "안유진",
        nick: "유진19",
        email: "yujin19@example.com",
        overallRank: 19,
        overallScore: 570,
        praiseRank: 19,
        praiseScore: 120,
        solveRank: 19,
        solveScore: 290,
        battleRank: 19,
        battleScore: 160,
    },
    {
        id: "20",
        name: "백준호",
        nick: "준호20",
        email: "junho20@example.com",
        overallRank: 20,
        overallScore: 550,
        praiseRank: 20,
        praiseScore: 110,
        solveRank: 20,
        solveScore: 280,
        battleRank: 20,
        battleScore: 160,
    },
    {
        id: "21",
        name: "김수현",
        nick: "수현21",
        email: "soohyun21@example.com",
        overallRank: 21,
        overallScore: 530,
        praiseRank: 21,
        praiseScore: 100,
        solveRank: 21,
        solveScore: 270,
        battleRank: 21,
        battleScore: 160,
    },
    {
        id: "22",
        name: "이지훈",
        nick: "지훈22",
        email: "jihoon22@example.com",
        overallRank: 22,
        overallScore: 510,
        praiseRank: 22,
        praiseScore: 90,
        solveRank: 22,
        solveScore: 260,
        battleRank: 22,
        battleScore: 160,
    },
    {
        id: "23",
        name: "임하나",
        nick: "하나23",
        email: "hana23@example.com",
        overallRank: 23,
        overallScore: 490,
        praiseRank: 23,
        praiseScore: 80,
        solveRank: 23,
        solveScore: 250,
        battleRank: 23,
        battleScore: 160,
    },
    {
        id: "24",
        name: "장성호",
        nick: "성호24",
        email: "sungho24@example.com",
        overallRank: 24,
        overallScore: 470,
        praiseRank: 24,
        praiseScore: 70,
        solveRank: 24,
        solveScore: 240,
        battleRank: 24,
        battleScore: 160,
    },
    {
        id: "25",
        name: "김하늘",
        nick: "하늘25",
        email: "haneul25@example.com",
        overallRank: 25,
        overallScore: 450,
        praiseRank: 25,
        praiseScore: 60,
        solveRank: 25,
        solveScore: 230,
        battleRank: 25,
        battleScore: 160,
    },
    {
        id: "26",
        name: "이진우",
        nick: "진우26",
        email: "jinwoo26@example.com",
        overallRank: 26,
        overallScore: 430,
        praiseRank: 26,
        praiseScore: 50,
        solveRank: 26,
        solveScore: 220,
        battleRank: 26,
        battleScore: 160,
    },
    {
        id: "27",
        name: "한예슬",
        nick: "예슬27",
        email: "yesul27@example.com",
        overallRank: 27,
        overallScore: 410,
        praiseRank: 27,
        praiseScore: 40,
        solveRank: 27,
        solveScore: 210,
        battleRank: 27,
        battleScore: 160,
    },
    {
        id: "28",
        name: "박서준",
        nick: "서준28",
        email: "seojun28@example.com",
        overallRank: 28,
        overallScore: 390,
        praiseRank: 28,
        praiseScore: 30,
        solveRank: 28,
        solveScore: 200,
        battleRank: 28,
        battleScore: 160,
    },
    {
        id: "29",
        name: "윤지수",
        nick: "지수29",
        email: "jisu29@example.com",
        overallRank: 29,
        overallScore: 370,
        praiseRank: 29,
        praiseScore: 20,
        solveRank: 29,
        solveScore: 190,
        battleRank: 29,
        battleScore: 160,
    },
    {
        id: "30",
        name: "오지민",
        nick: "지민30",
        email: "jimin30@example.com",
        overallRank: 30,
        overallScore: 350,
        praiseRank: 30,
        praiseScore: 10,
        solveRank: 30,
        solveScore: 180,
        battleRank: 30,
        battleScore: 160,
    },
    {
        id: "31",
        name: "김현수",
        nick: "현수31",
        email: "hyunsoo31@example.com",
        overallRank: 31,
        overallScore: 330,
        praiseRank: 31,
        praiseScore: 9,
        solveRank: 31,
        solveScore: 170,
        battleRank: 31,
        battleScore: 160,
    },
    {
        id: "32",
        name: "이재영",
        nick: "재영32",
        email: "jaeyoung32@example.com",
        overallRank: 32,
        overallScore: 310,
        praiseRank: 32,
        praiseScore: 8,
        solveRank: 32,
        solveScore: 160,
        battleRank: 32,
        battleScore: 160,
    },
    {
        id: "33",
        name: "박수빈",
        nick: "수빈33",
        email: "soobin33@example.com",
        overallRank: 33,
        overallScore: 290,
        praiseRank: 33,
        praiseScore: 7,
        solveRank: 33,
        solveScore: 150,
        battleRank: 33,
        battleScore: 160,
    },
    {
        id: "34",
        name: "조민준",
        nick: "민준34",
        email: "minjun34@example.com",
        overallRank: 34,
        overallScore: 270,
        praiseRank: 34,
        praiseScore: 6,
        solveRank: 34,
        solveScore: 140,
        battleRank: 34,
        battleScore: 160,
    },
    {
        id: "35",
        name: "정해린",
        nick: "해린35",
        email: "haerin35@example.com",
        overallRank: 35,
        overallScore: 250,
        praiseRank: 35,
        praiseScore: 5,
        solveRank: 35,
        solveScore: 130,
        battleRank: 35,
        battleScore: 160,
    },
    {
        id: "36",
        name: "한수정",
        nick: "수정36",
        email: "soojung36@example.com",
        overallRank: 36,
        overallScore: 230,
        praiseRank: 36,
        praiseScore: 4,
        solveRank: 36,
        solveScore: 120,
        battleRank: 36,
        battleScore: 160,
    },
    {
        id: "37",
        name: "김하린",
        nick: "하린37",
        email: "harin37@example.com",
        overallRank: 37,
        overallScore: 210,
        praiseRank: 37,
        praiseScore: 3,
        solveRank: 37,
        solveScore: 110,
        battleRank: 37,
        battleScore: 160,
    },
    {
        id: "38",
        name: "오준호",
        nick: "준호38",
        email: "junho38@example.com",
        overallRank: 38,
        overallScore: 190,
        praiseRank: 38,
        praiseScore: 2,
        solveRank: 38,
        solveScore: 100,
        battleRank: 38,
        battleScore: 160,
    },
    {
        id: "39",
        name: "장서윤",
        nick: "서윤39",
        email: "seoyoon39@example.com",
        overallRank: 39,
        overallScore: 170,
        praiseRank: 39,
        praiseScore: 1,
        solveRank: 39,
        solveScore: 90,
        battleRank: 39,
        battleScore: 160,
    },
    {
        id: "40",
        name: "문채원",
        nick: "채원40",
        email: "chaewon40@example.com",
        overallRank: 40,
        overallScore: 150,
        praiseRank: 40,
        praiseScore: 0,
        solveRank: 40,
        solveScore: 80,
        battleRank: 40,
        battleScore: 160,
    },
    {
        id: "41",
        name: "윤채은",
        nick: "채은41",
        email: "chaeun41@example.com",
        overallRank: 41,
        overallScore: 130,
        praiseRank: 41,
        praiseScore: 0,
        solveRank: 41,
        solveScore: 70,
        battleRank: 41,
        battleScore: 160,
    },
    {
        id: "42",
        name: "강지민",
        nick: "지민42",
        email: "jimin42@example.com",
        overallRank: 42,
        overallScore: 110,
        praiseRank: 42,
        praiseScore: 0,
        solveRank: 42,
        solveScore: 60,
        battleRank: 42,
        battleScore: 160,
    },
    {
        id: "43",
        name: "조민지",
        nick: "민지43",
        email: "minji43@example.com",
        overallRank: 43,
        overallScore: 90,
        praiseRank: 43,
        praiseScore: 0,
        solveRank: 43,
        solveScore: 50,
        battleRank: 43,
        battleScore: 160,
    },
    {
        id: "44",
        name: "김나은",
        nick: "나은44",
        email: "naeun44@example.com",
        overallRank: 44,
        overallScore: 70,
        praiseRank: 44,
        praiseScore: 0,
        solveRank: 44,
        solveScore: 40,
        battleRank: 44,
        battleScore: 160,
    },
    {
        id: "45",
        name: "이시원",
        nick: "시원45",
        email: "siwon45@example.com",
        overallRank: 45,
        overallScore: 50,
        praiseRank: 45,
        praiseScore: 0,
        solveRank: 45,
        solveScore: 30,
        battleRank: 45,
        battleScore: 160,
    },
    {
        id: "46",
        name: "박채린",
        nick: "채린46",
        email: "chaerin46@example.com",
        overallRank: 46,
        overallScore: 30,
        praiseRank: 46,
        praiseScore: 0,
        solveRank: 46,
        solveScore: 20,
        battleRank: 46,
        battleScore: 160,
    },
    {
        id: "47",
        name: "최영우",
        nick: "영우47",
        email: "youngwoo47@example.com",
        overallRank: 47,
        overallScore: 20,
        praiseRank: 47,
        praiseScore: 0,
        solveRank: 47,
        solveScore: 10,
        battleRank: 47,
        battleScore: 160,
    },
    {
        id: "48",
        name: "이민지",
        nick: "민지48",
        email: "minji48@example.com",
        overallRank: 48,
        overallScore: 15,
        praiseRank: 48,
        praiseScore: 0,
        solveRank: 48,
        solveScore: 5,
        battleRank: 48,
        battleScore: 160,
    },
    {
        id: "49",
        name: "윤도현",
        nick: "도현49",
        email: "dohyun49@example.com",
        overallRank: 49,
        overallScore: 10,
        praiseRank: 49,
        praiseScore: 0,
        solveRank: 49,
        solveScore: 0,
        battleRank: 49,
        battleScore: 160,
    },
    {
        id: "50",
        name: "오준수",
        nick: "준수50",
        email: "joonsoo50@example.com",
        overallRank: 50,
        overallScore: 5,
        praiseRank: 50,
        praiseScore: 0,
        solveRank: 50,
        solveScore: 0,
        battleRank: 50,
        battleScore: 160,
    },
    {
        id: "51",
        name: "최진수",
        nick: "구름코더",
        email: "goormcoder@example.com",
        overallRank: 3837,
        overallScore: 1124 + 1320 + 950,
        praiseRank: 2023,
        praiseScore: 1124,
        solveRank: 2321,
        solveScore: 1320,
        battleRank: 4083,
        battleScore: 950,
    }
];